version: '3.4'

services:
  eshopservices.api.author:
    image: ${DOCKER_REGISTRY-}eshopservicesapiauthor
    build:
      context: .
      dockerfile: EShopServices.Api.Author/Dockerfile
  eshopservices.api.book:
    image: ${DOCKER_REGISTRY-}eshopservicesapibook
    build:
      context: .
      dockerfile: EShopServices.Api.Book/Dockerfile

  eshopservices.api.cart:
    image: ${DOCKER_REGISTRY-}eshopservicesapicart
    build:
      context: .
      dockerfile: EShopServices.Api.Cart/Dockerfile

  eshopservices.api.gateway:
    image: ${DOCKER_REGISTRY-}eshopservicesapigateway
    build:
      context: .
      dockerfile: EShopServices.Api.Gateway/Dockerfile

networks:
    default:
        external:
            name: microservicenet



